<?php
use JeroenDesloovere\VCard\VCard;
class VcardExport
{
    public function contactVcardExportService($complete_array)
    {
        require_once 'vendor/Behat-Transliterator/Transliterator.php';
        require_once 'vendor/jeroendesloovere-vcard/VCard.php';
        // define vcard
        $vcardObj = new VCard();
        // add personal data    
        $send="";  
        $vcardObj->addName($complete_array[0]. " " .$complete_array[1]);
        // $vcardObj->addBirthday('1994-08-27');
        $vcardObj->addEmail($complete_array[2],'WORK');
        $vcardObj->addEmail($complete_array[12],'PREF;HOME'); 
        $vcardObj->addPhoneNumber($complete_array[3],'CELL');       
        $vcardObj->addPhoneNumber($complete_array[13],'HOME');
        $vcardObj->addPhoneNumber($complete_array[14],'WORK');       
        $vcardObj->addAddress($complete_array[10],'HOME');  
        $vcardObj->addAddress($complete_array[15],'PREF;WORK');      
        // $vcardObj->addImpp('abc@gmail.com'); 
        $vcardObj->addNickName($complete_array[8]);       
        $vcardObj->addRole($complete_array[5]);  
        $vcardObj->addCompany($complete_array[9],$complete_array[6]);   
        $vcardObj->addJobtitle($complete_array[4]); 
        $vcardObj->addUrl($complete_array[11],'PREF;WORK'); 
        $vcardObj->addNote($complete_array[7]); 
        $vcardObj->addProdID("VCF generated by CSVTOVCF");              
        $vcardObj->download();
}
}
?>